"""Environment clone planning for the isolated M-ABD Newton runtime."""

from __future__ import annotations

import subprocess
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from mabd_reproduction.environment import MABD_ENV_ROOT, REFERENCE_ENV_ROOT


DEFAULT_CONDA = Path("/cpfs/user/zhuzihou/conda-managed/miniforge3/bin/conda")


class EnvironmentCloneError(RuntimeError):
    """Raised when an environment clone path would violate isolation rules."""


def _resolved(path: Path) -> Path:
    return path.expanduser().resolve(strict=False)


def _is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
    except ValueError:
        return False
    return True


def _with_trailing_slash(path: Path) -> str:
    return f"{path}/"


def _base_plan(
    *,
    reference_env: Path,
    target_env: Path,
    conda_executable: Path,
    sync_existing: bool,
) -> dict[str, Any]:
    return {
        "reference_environment": str(reference_env),
        "target_environment": str(target_env),
        "conda_executable": str(conda_executable),
        "sync_existing": sync_existing,
        "non_pollution": {
            "mutates_reference_environment": False,
            "uses_reference_python": False,
            "uses_ambient_python": False,
            "installs_into_ambient_python": False,
            "target_is_project_environment": _resolved(target_env) == _resolved(MABD_ENV_ROOT),
            "reference_is_source_only": True,
        },
    }


def build_clone_plan(
    *,
    reference_env: Path = REFERENCE_ENV_ROOT,
    target_env: Path = MABD_ENV_ROOT,
    conda_executable: Path = DEFAULT_CONDA,
    sync_existing: bool = False,
) -> dict[str, Any]:
    """Return the command plan for cloning or synchronizing the project env.

    The plan is intentionally conservative: an existing target is not changed unless
    ``sync_existing`` is explicitly requested.
    """

    reference_env = Path(reference_env)
    target_env = Path(target_env)
    conda_executable = Path(conda_executable)
    reference_resolved = _resolved(reference_env)
    target_resolved = _resolved(target_env)

    if reference_resolved == target_resolved:
        raise EnvironmentCloneError("reference and target environments must be different paths")
    if _is_relative_to(target_resolved, reference_resolved):
        raise EnvironmentCloneError("target environment must not be inside the reference environment")
    if _is_relative_to(reference_resolved, target_resolved):
        raise EnvironmentCloneError("reference environment must not be inside the target environment")

    plan = _base_plan(
        reference_env=reference_env,
        target_env=target_env,
        conda_executable=conda_executable,
        sync_existing=sync_existing,
    )

    if not reference_env.exists():
        return {
            **plan,
            "status": "reference_missing",
            "can_execute": False,
            "commands": [],
            "operator_action": f"create or mount reference environment first: {reference_env}",
        }

    if target_env.exists() and not sync_existing:
        return {
            **plan,
            "status": "target_exists",
            "can_execute": False,
            "commands": [],
            "operator_action": "pass --sync-existing to refresh the project env from the reference env",
        }

    if target_env.exists() and sync_existing:
        return {
            **plan,
            "status": "ready_to_sync_existing",
            "can_execute": True,
            "commands": [["rsync", "-a", "--delete", _with_trailing_slash(reference_env), _with_trailing_slash(target_env)]],
            "operator_action": "execute explicit target sync",
        }

    return {
        **plan,
        "status": "ready_to_clone",
        "can_execute": True,
        "commands": [[str(conda_executable), "create", "-y", "-p", str(target_env), "--clone", str(reference_env)]],
        "operator_action": "execute isolated target clone",
    }


def execute_clone_plan(plan: Mapping[str, Any]) -> dict[str, Any]:
    """Execute a clone plan generated by :func:`build_clone_plan`."""

    if not plan.get("can_execute"):
        return {**dict(plan), "executed": False}

    results: list[dict[str, Any]] = []
    for command in plan.get("commands", []):
        if not isinstance(command, Sequence) or isinstance(command, (str, bytes)):
            return {
                **dict(plan),
                "status": "invalid_command_plan",
                "executed": False,
                "command_results": results,
            }
        result = subprocess.run(
            [str(part) for part in command],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        results.append(
            {
                "command": [str(part) for part in command],
                "returncode": result.returncode,
                "stdout": result.stdout,
                "stderr": result.stderr,
            }
        )
        if result.returncode != 0:
            return {
                **dict(plan),
                "status": "command_failed",
                "executed": True,
                "command_results": results,
            }

    completed_status = "sync_completed" if plan.get("status") == "ready_to_sync_existing" else "clone_completed"
    return {
        **dict(plan),
        "status": completed_status,
        "executed": True,
        "command_results": results,
    }
